spring:
  application:
    name: charMe
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  data:
    mongodb:
      uri: mongodb://localhost:27017/charself
      
  datasource:
    url:  jdbc:mysql://139.199.86.201:3306/charself?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    
  rabbitmq:
    host: 139.199.86.201
    port: 5672
    username: admin
    password: zy1314520

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yzeng.charme.entity
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql